name: vrna_app_mobile
description: VRNA PLEX Movie Experience

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: any
  dio: any
  http: 0.13.3
  rxdart: ^0.26.0-nullsafety.1
  provider: ^5.0.0
  shared_preferences: any
  fluttertoast: ^8.0.7
  image_picker: any
  flutter_speed_dial: ^1.2.4
  intl: any
  connectivity: ^3.0.6
  carousel_slider: ^4.0.0
  flick_video_player: 0.3.1
  video_player: 2.1.12
  # video_player_web: any
  video_player_web_hls: any  
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.5.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  flutter_rating_bar: ^4.0.0 
  localstorage: any
  platform_device_id: ^1.0.1
  expansion_tile_card: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # unique_identifier: ^0.0.3
  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
  assets:
    - assets/logo.png
    - assets/logo_header.png
    - assets/images/
    - assets/fb.png
    - assets/google.png   
    - assets/backarrow.png   
    - assets/burger_menu.png   
    - assets/images/movie1.png
    - assets/images/movie4.png  
    - assets/card.png    
    - assets/profile.png    
    - assets/loginbg.png
    - assets/play.png    
    - assets/watchtrailer.png
    - assets/recent.png
    - assets/rent.png

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf-ui-display-light.ttf
 
    - family: SF UI Display Black
      fonts:
        - asset: assets/fonts/sf-ui-display-black.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
